#!/bin/sh

err=

if [ "$(git config --bool hooks.pre-commit.no-gitcheck)" != true ]; then
  if ! git diff --check --cached; then
    err=1
  fi
fi

if [ "$(git config --bool hooks.pre-commit.no-editorconfig)" != true ]; then
  if type editorconfig-checker 1>/dev/null 2>&1; then
    if ! git diff -z --cached --name-only --diff-filter=d --no-renames --ignore-submodules=all | xargs --null --no-run-if-empty editorconfig-checker; then
      err=1
    fi
  fi
fi

if [ "$(git config --bool hooks.pre-commit.no-gitleaks)" != true ]; then
  if ! gitleaks protect --verbose --redact --staged --no-banner --log-level=warn; then
    err=1
  fi
fi

if [ $err ]; then
  exit 1
fi
