#!/bin/bash

set -eu

err_usage (){
  {
    echo "${0##*/}: $*"
    echo
    echo "Usage: ${0##*/} [-u] <directory>"
  }  1>&2
  exit 1
}

err_exit (){
  err "$@"
  exit 1
}
err (){
  {
    echo "${0##*/}: $*"
  }  1>&2
}

opt_u=
dirs=()

while [ $# -ne 0 ]; do
  if [ "$1" == "-u" ]; then
    opt_u=1
  elif [ "${1#-}" != "${1}" ]; then
    err_exit "illegal option ${1}"
  else
    dirs+=( "$1" )
  fi
  shift
done

if [ "${#dirs[@]}" -eq 0 ]; then
  err_usage "must be specified directory"
fi

for dir in "${dirs[@]}"; do
  if [ ! -d "$dir" ]; then
    err_exit "$dir is not directory"
  fi
done

for dir in "${dirs[@]}"; do

  realdir="$(realpath -- "$dir")"
  mnt="$HOME/.bind/${realdir#/}"

  is_mounted(){
    [ "$(cat /etc/mtab | cut -d' ' -f2 | grep -F "$realdir")" == "$realdir" ]
  }

  if [[ -z $opt_u ]]; then
    if is_mounted; then
      echo "$dir is mounted"
    else
      mkdir -p "$mnt"
      sudo umount "$mnt" 2>/dev/null &&:
      sudo mount --bind -o user "$mnt" "$realdir"
      ln -sfn /dev/null "$realdir/.workbind"
      echo "$dir ok ... bind $mnt"
    fi
  else
    if ! is_mounted; then
      echo "$dir is not mounted"
    else
      sudo umount "$realdir"
      echo "$dir ok ... umount $mnt"
    fi
  fi
done
