#!/bin/bash

php=$(type -p php)

if [ -z "$php" ]; then
	echo "php command not found" 1>&2
	exit 1
fi

phar=$(dirname "$php")/pharcommand.phar

if [ -z "$phar" ]; then
	echo "pharcommand.phar not found" 1>&2
	exit 1
fi

"$php" "$phar" "$@"
