#!/usr/bin/env bash

# Usage: phplive [options] [dir]
#
# Options:
#   -o         Open WebBrowser
#   -w         Enable LiveReload
#   -x         Enable LiveReload on proxy mode
#   -p port    Listening PortNumber on WebServer
#
# Arguments:
#   dir        Document Root
# END

set -ue

function usage()
{
    cat $0 | sed -r -n '
        /^# END/q
        /^# Usage/,//{
            s/^# ?//
            p
        }
    '
    exit 1
}

open=0
live=0
proxy=0
port=9876
root=.
file=

while getopts owxp: OPT; do
    case $OPT in
        o)  open=1
            ;;
        w)  live=1
            ;;
        x)  proxy=35729
            ;;
        p)  port=$OPTARG
            ;;
        \?) usage
            ;;
    esac
done

shift $((OPTIND - 1))

if [ $# -gt 0 ]; then
    if [ -d "$1" ]; then
        root=${1%/}
        file=
    else
        root=$(dirname "$1")
        file=$(basename "$1")
    fi
fi

if [ "$open" -ne 0 ]; then
    if [ -n "${WINDIR-}" ]; then
        ( sleep 1 && start "http://127.0.0.1:$port/$file" )&
    else
        ( sleep 1 && open "http://127.0.0.1:$port/$file" )&
    fi
fi

if [ "$proxy" -ne 0 ]; then
    livereloadx -p $port -y http://localhost:$proxy &
    php -S "0.0.0.0:$proxy" -t "$root"
elif [ "$live" -ne 0 ]; then
    livereloadx &
    php -S "0.0.0.0:$port" -t "$root"
else
    php -S "0.0.0.0:$port" -t "$root"
fi
