#!/bin/bash

if [ ! -x "$CONEMU_BIN" ]; then
  CONEMU_BIN="C:\\Program Files\\ConEmu\\ConEmu64.exe"
  if [ ! -x "$CONEMU_BIN" ]; then
    echo "You should be set \$CONEMU_BIN Environment variable." 1>&2
    exit 1
  fi
fi

start "" "$CONEMU_BIN" -NoSingle -cmd "bash --login"
