#!/bin/bash

if [ "$1" == "-#" ]; then
  shift
  filter() {
    sed 's/^/# /'
  }
else
  filter() {
    cat
  }
fi

if [ $# -eq 0 ]; then
  exec 2>&1
  filter | tee /dev/stderr | { iconv -t UTF-16LE; } | /c/Windows/System32/clip.exe
else
  echo "$*"
  echo -n "$*" | filter | { iconv -t UTF-16LE; } | /c/Windows/System32/clip.exe
fi
