#!/bin/bash

# git/tig から `+123 file` の形式で呼ばれたときに `-w -g file:123:1` で code を実行する

line=1
if [[ $1 =~ ^\+[0-9]+$ ]]; then
  line=${1#+}
  shift
fi
file=$1

VSCODE_PATH="$(wslpath -u 'C:\\Program Files\\Microsoft VS Code')"
ELECTRON="$VSCODE_PATH/Code.exe"

if [ ! -x "$ELECTRON" ]; then
  printf "%s is not executable" "$ELECTRON"
  exit 1
fi

export WSLENV=ELECTRON_RUN_AS_NODE/w:$WSLENV
export ELECTRON_RUN_AS_NODE=1
CLI=$(wslpath -m "$VSCODE_PATH/resources/app/out/cli.js")
"$ELECTRON" "$CLI" -w -g "$(wslpath -wa -- "$file"):$line:1"
