#!/bin/bash

# vscode の統合ターミナル内だと爆速で開くのでそれを模倣する
# ただし vscode のウィンドウがフォアグラウンドにならないので別コマンドで対応
#
vscode_ipc_exec() {
  # /run/user/1000/vscode-ipc-*.sock を探すだけだと kiro とかも見つけてしまうので vscode-server の pid でフィルタする
  cmd="$(ls ~/.vscode-server/bin/*/node -t | head -1)"
  pattern="$(pidof "$cmd" | sed -e 's/ /,|,pid=/g' -e 's/^/,pid=/' -e 's/$/,/')"
  VSCODE_IPC_HOOK_CLI="$(ss -lxp | grep -F "${XDG_RUNTIME_DIR%/}/vscode-ipc" | grep -E "($pattern)" | head -1 | awk '{print $5}')"
  if [ ! -S "$VSCODE_IPC_HOOK_CLI" ]; then
    return
  fi
  VSCODE_BIN="$(ls ~/.vscode-server/bin/*/bin/remote-cli/code -t | head -1)"
  if [ ! -x "$VSCODE_BIN" ]; then
    return
  fi
  # この方法だとウィンドウがフォアグラウンドにならないため、フォアグラウンド化のためのコマンドを別途実行
  "$USERPROFILE/bin/win-activate-process.exe" "Visual Studio Code"
  export VSCODE_IPC_HOOK_CLI
  exec "$VSCODE_BIN" "$@"

  # VSCODE_IPC_HOOK_CLI="$(ss -lxp | grep -F "${XDG_RUNTIME_DIR%/}/vscode-ipc" | head -1 | awk '{print $5}')"
  # if [ ! -S "$VSCODE_IPC_HOOK_CLI" ]; then
  #   return
  # fi
  # VSCODE_BIN="$(ls ~/.vscode-server/bin/*/bin/remote-cli/code -t | head -1)"
  # if [ ! -x "$VSCODE_BIN" ]; then
  #   return
  # fi
  # win-activate-process.exe "Code.exe"
  # export VSCODE_IPC_HOOK_CLI
  # exec "$VSCODE_BIN" "$@"
}

vscode_path_detect() {
  VSCODE_PATH=

  [ ! -e "$VSCODE_PATH" ] && VSCODE_PATH="$USERPROFILE/AppData/Local/Programs/Microsoft VS Code"
  [ ! -e "$VSCODE_PATH" ] && VSCODE_PATH="$USERPROFILE/scoop/apps/vscode/current"
  [ ! -e "$VSCODE_PATH" ] && VSCODE_PATH="$(wslpath -u 'C:\\Program Files\\Microsoft VS Code')"

  if [ ! -x "$VSCODE_PATH/bin/code" ]; then
    printf "\"%s\" is not executable" "$VSCODE_PATH/bin/code"
    exit 1
  fi
}

vscode_exec() {
    #export VSCODE_WSL_DEBUG_INFO=true
    exec "$VSCODE_PATH/bin/code" "$@"
}

# .vscode/extensions/ms-vscode-remote.remote-wsl-0.81.0 のようなディレクトリを得るために Code.exe を実行している
# 遅いので別の方法で得ることで改善する
vscode_exec2() {
    pid="$(pgrep -f '.vscode/extensions/ms-vscode-remote.remote-wsl-.*/scripts/wslServer.sh')"
    [ -z "$pid" ] && return 1
    VSCODE_WSL_EXT_LOCATION="$(cat /proc/$pid/environ | grep -z '^VSCODE_WSL_EXT_LOCATION=' | cut -z -d= -f2- | tr -d '\0')"
    [ -z "$VSCODE_WSL_EXT_LOCATION" ] && return 1
    COMMIT="$(cat /proc/$pid/cmdline | cut -d $'\0' -f 3)"
    [ -z "$COMMIT" ] && return 1

    #export VSCODE_WSL_DEBUG_INFO=true
    export WSLENV="ELECTRON_RUN_AS_NODE/w:$WSLENV"
    exec "$VSCODE_WSL_EXT_LOCATION/scripts/wslCode.sh" "$COMMIT" stable "$VSCODE_PATH/Code.exe" code .vscode-server "$@"
}

stdin=
for opt in "$@"; do
  case "$opt" in
    -)
      stdin=1
      ;;
  esac
done

# パイプとかで stdin から読むときは ipc だと動きがおかしい
if [ -z "$stdin" ]; then
  vscode_ipc_exec "$@"
fi
vscode_path_detect
vscode_exec2 "$@"
vscode_exec "$@"
