#!/bin/bash

# この方法なら爆速で開くけどウィンドウがフォアグラウンドにならないので不便 → 廃止
#
# vscode_ipc_exec() {
#   VSCODE_IPC_HOOK_CLI="$(ls /wslg/runtime-dir/vscode-ipc-* -t | head -1)"
#   if [ ! -S "$VSCODE_IPC_HOOK_CLI" ]; then
#     return
#   fi
#   VSCODE_BIN="$(ls ~/.vscode-server/bin/*/bin/remote-cli/code -t | head -1)"
#   if [ ! -x "$VSCODE_BIN" ]; then
#     return
#   fi
#   export VSCODE_IPC_HOOK_CLI
#   exec "$VSCODE_BIN" "$@"
# }
# vscode_ipc_exec "$@"

VSCODE_PATH=

[ ! -e "$VSCODE_PATH" ] && VSCODE_PATH="$USERPROFILE/AppData/Local/Programs/Microsoft VS Code"
[ ! -e "$VSCODE_PATH" ] && VSCODE_PATH="$USERPROFILE/scoop/apps/vscode/current"
[ ! -e "$VSCODE_PATH" ] && VSCODE_PATH="$(wslpath -u 'C:\\Program Files\\Microsoft VS Code')"

if [ ! -x "$VSCODE_PATH/bin/code" ]; then
    printf "\"%s\" is not executable" "$VSCODE_PATH/bin/code"
    exit 1
fi

vscode_exec() {
    export VSCODE_WSL_DEBUG_INFO=true
    exec "$VSCODE_PATH/bin/code" "$@"
}

vscode_exec2() {
    # .vscode/extensions/ms-vscode-remote.remote-wsl-0.81.0 のようなディレクトリを得るために exe を実行しており
    # 遅いので起動済の vscode プロセスの環境変数から得る

    pid="$(pgrep -f '.vscode/extensions/ms-vscode-remote.remote-wsl-.*/scripts/wslServer.sh')"
    [ -z "$pid" ] && return 1

    VSCODE_WSL_EXT_LOCATION="$(cat /proc/$pid/environ | grep -z '^VSCODE_WSL_EXT_LOCATION=' | cut -z -d= -f2- | tr -d '\0')"
    [ -z "$VSCODE_WSL_EXT_LOCATION" ] && return 1

    eval "$(grep '^COMMIT=' < "$VSCODE_PATH/bin/code")"
    # COMMIT="$(cat /proc/$pid/cmdline | cut -d $'\0' -f 3)"
    [ -z "$COMMIT" ] && return 1

    export WSLENV="ELECTRON_RUN_AS_NODE/w:$WSLENV"
    #export VSCODE_WSL_DEBUG_INFO=true
    exec "$VSCODE_WSL_EXT_LOCATION/scripts/wslCode.sh" "$COMMIT" stable "$VSCODE_PATH/Code.exe" code .vscode-server "$@"
}

vscode_exec2 "$@" || vscode_exec "$@"
