#!/bin/bash

VSCODE_PATH="$(wslpath -u 'C:\\Program Files\\Microsoft VS Code')"

if [ ! -x "$VSCODE_PATH/bin/code" ]; then
  printf "%e is not executable" "$VSCODE_PATH/bin/code"
  exit 1
fi

if [ ! -x "$VSCODE_PATH/Code.exe" ]; then
  printf "%e is not executable" "$VSCODE_PATH/Code.exe"
  exit 1
fi

exec "$VSCODE_PATH/bin/code" "$@"
