#!/bin/bash

arr=(
  "$USERPROFILE/scoop/apps/vscode/current/bin/code"
  "$USERPROFILE/scoop/apps/vscode/current/Code.exe"
  "$USERPROFILE/scoop/apps/winmerge/current/WinMergeU.exe"
  "$USERPROFILE/scoop/apps/unison/current/unison.exe"
)

for x in "${arr[@]}"; do
  if [ -e "$x" ]; then
    chmod +x -v "$x"
  fi
done
