#!/bin/bash

set -eu

dir=$PWD

while [ ! -e "$dir/.unison/fsv-sync.prf" ]; do
  dir="$(dirname -- "$dir")"
  if [ "$dir" == "/" ]; then
    echo ".unison/fsv-sync.prf notfound"
    exit
  fi
done

cd "$dir"

cat <<EOS>.unison/.fsv-sync.bat
@echo off
color 1f
set UNISON=.unison
cd %~dp0\..
unison.exe fsv-sync -auto $*
EOS

cmd.exe /C ".unison\\.fsv-sync.bat"
rm -f .unison/.fsv-sync.bat
