#!/bin/bash

if [ -e "$USERPROFILE/scoop/apps/winmerge/current/WinMergeU.exe" ]; then
    prog=$(wslpath -wa "$USERPROFILE/scoop/apps/winmerge/current/WinMergeU.exe")
else
    prog='C:\Program Files\WinMerge\WinMergeU.exe'
fi

exec wslexec "$prog" "$1"

#cmd = \"WinMergeU.exe\" -r -e -u -al \
#-dl Local -wm -dm Remote -wr -dr 共通祖先  \
#    \"`wslpath -wa $LOCAL`\" \
#    \"`wslpath -wa $REMOTE`\" \
#    \"`wslpath -wa $BASE`\" \
#    -o \"`wslpath -wa $MERGED`\"
