#!/bin/bash

arr=(
  "$USERPROFILE/scoop/apps/winmerge/current/WinMergeU.exe"
  "$USERPROFILE/AppData/Local/Programs/WinMerge/WinMergeU.exe"
  '/c/Program Files/WinMerge/WinMergeU.exe'
)

for prog in "${arr[@]}"; do
  if [ -e "$prog" ]; then
    prog=$(wslpath -wa "$prog")
    exec wslexec "$prog" -e -u -r -x -wl "$1" "$2"
  fi
done
