#!/bin/bash

prog='C:\Program Files\WinMerge\WinMergeU.exe'

exec wslexec "$prog" "$1"

#cmd = \"WinMergeU.exe\" -r -e -u -al \
#-dl Local -wm -dm Remote -wr -dr 共通祖先  \
#    \"`wslpath -wa $LOCAL`\" \
#    \"`wslpath -wa $REMOTE`\" \
#    \"`wslpath -wa $BASE`\" \
#    -o \"`wslpath -wa $MERGED`\"
