#!/bin/bash

if [ -e "$USERPROFILE/scoop/apps/winmerge/current/WinMergeU.exe" ]; then
    prog=$(wslpath -wa "$USERPROFILE/scoop/apps/winmerge/current/WinMergeU.exe")
else
    prog='C:\Program Files\WinMerge\WinMergeU.exe'
fi

exec wslexec "$prog" -e -u -r -x -wl "$1" "$2"
