#!/bin/bash

prog=$(wslpath -u 'C:\Program Files\WinMerge\WinMergeU.exe')

exec "$prog" "$(wslpath -wa "$1")"

#cmd = \"WinMergeU.exe\" -r -e -u -al \
#-dl Local -wm -dm Remote -wr -dr 共通祖先  \
#    \"`wslpath -wa $LOCAL`\" \
#    \"`wslpath -wa $REMOTE`\" \
#    \"`wslpath -wa $BASE`\" \
#    -o \"`wslpath -wa $MERGED`\"
