#!/bin/bash

set -eu

opt_v=

while getopts v OPT; do
  case "$OPT" in
    v) opt_v=1 ;;
    *) exit 1 ;;
  esac
done

shift "$((OPTIND - 1))"

if [[ -e /tmp/ssid ]]; then
  find /tmp/ssid -mmin +60 -exec rm -f -- {} \;
fi
if [[ ! -e /tmp/ssid ]]; then
  /c/Windows/System32/netsh.exe wlan show interfaces | grep -w SSID > /tmp/ssid
fi

if [[ $opt_v ]]; then
  grep -v "$1" </tmp/ssid >/dev/null
else
  grep "$1" </tmp/ssid >/dev/null
fi
