#!/bin/bash

set -eu

function usage()
{
    echo "Usage: $(basename "$0") <command> [path]" 1>&2
    exit 1
}

if [ -z "${1:-}" ]; then
    usage
fi

command=

case "$1" in
    status)
        command=repostatus
        ;;
    *)
        command=$1
        ;;
esac

path=${2:-.}

#if [ -z "${2:-}" ]; then
#    path=.
#else
#    path=$2
#fi

prog='C:\Program Files\TortoiseGit\bin\TortoiseGitProc.exe'

wslexec "$prog" "/command:$command" "/path:$path"
