#!/bin/bash

set -eu

function usage()
{
    echo "Usage: $(basename "$0") <command> [path]" 1>&2
    exit 1
}

: ${TGIT_BIN_DIR:=/mnt/c/Program Files/TortoiseGit/bin}

if [ ! -x "$TGIT_BIN_DIR/TortoiseGitProc.exe" ]; then
    echo "You should be set \$TGIT_BIN_DIR Environment variable." 1>&2
    exit 1
fi

if [ -z "${1:-}" ]; then
    usage
fi

command=

case "$1" in
    status)
        command=repostatus
        ;;
    *)
        command=$1
        ;;
esac

path=${2:-.}

#if [ -z "${2:-}" ]; then
#    path=.
#else
#    path=$2
#fi

"$TGIT_BIN_DIR/TortoiseGitProc.exe" "/command:$command" "/path:$path"
