#!/bin/bash

case "$1" in
  --file)
    shift
    if [ -n "$2" -a "$2" -ne "0" ]; then
      set -- "$1:$2"
    else
      set -- "$1"
    fi
    ;;

  --*)
    shift
    ;;
esac


echo -n "Copy to clipboard ... "
echo -n "$*" | clip
