#!/bin/bash

case "$1" in
  --file)
    shift
    if [ -n "$2" -a "$2" -ne "0" ]; then
      set -- "$1:$2"
    else
      set -- "$1"
    fi
    ;;
  
  --diff)
    shift
    eval "$1"
    set -- "commit=$commit file=$file lineno=$lineno lineno_old=$lineno_old"
    if [ -z "$file" ]; then
      set -- "$commit"
    elif [ -n "$lineno" -a "$lineno" -ne "0" ]; then
      set -- "$commit" "$file:$lineno"
    elif [ -n "$lineno_old" -a "$lineno_old" -ne "0" ]; then
      set -- "$commit" "$file:$lineno_old"
    else
      set -- "$commit" "$file"
    fi
    ;;

  --*)
    shift
    ;;
esac


echo -n "Copy to clipboard ... "
echo -n "$*" | clip
