#!/bin/bash

arr=(
  "$USERPROFILE/scoop/apps/winmerge/current/WinMergeU.exe"
  "$USERPROFILE/AppData/Local/Programs/WinMerge/WinMergeU.exe"
  '/c/Program Files/WinMerge/WinMergeU.exe'
)

export TMPDIR=$(realpath "$USERPROFILE/AppData/Local/Temp")

for prog in "${arr[@]}"; do
  if [ -e "$prog" ]; then
    prog=$(wslpath -wa "$prog")
    # -e Escキーで閉じる
    # -u MRU にパスを追加しない
    # -r 再帰比較
    # -x 差異の無いファイルではすぐに閉じる
    exec wslexec "$prog" -e -u -r -x "$@"
  fi
done

echo 'WinMergeU.exe notfound' 1>&2
