#!/bin/bash

if [ -e "$USERPROFILE/scoop/apps/winmerge/current/WinMergeU.exe" ]; then
    prog=$(wslpath -wa "$USERPROFILE/scoop/apps/winmerge/current/WinMergeU.exe")
else
    prog='C:\Program Files\WinMerge\WinMergeU.exe'
fi

wslexec "$prog" /r /e /u /f '*.*' "$@"
