#!/bin/bash

set -eu

winexec="$(wslpath -u "C:\Users\\$USER\winexec.exe")"

if [[ ! -x "$winexec" ]]; then
  echo "download winexec.exe ..."

  url="https://github.com/ngyuki/go-winexec/releases/latest"
  latest=$(curl -fSIL "$url" | tr -d '\r' | awk -F'/' 'BEGIN{IGNORECASE=1}/^Location:/{print $NF}')
  url="https://github.com/ngyuki/go-winexec/releases/download/${latest}/winexec.exe"
  curl -fSL "$url" -o "$winexec"
  chmod +x "$winexec"

  echo
  echo "installed $winexec"
fi

args=()

for x in "$@"; do
  if [ -e "$x" ]; then
    args+=( "$(wslpath -wa -- "$x")" )
  else
    args+=( "$x" )
  fi
done

exec "$winexec" "${args[@]}"
