#!/bin/bash

# wsl のパスを windows のパスに変換しつつ Win32 exe を実行

cmd=$1
shift
if [ ! -e "$cmd" ]; then
  cmd="$(wslpath -u -- "$cmd")"
fi
args=()
for x in "$@"; do
  if [ -e "$x" ]; then
    args+=( "$(wslpath -wa -- "$x")" )
  else
    args+=( "$x" )
  fi
done

exec "$cmd" "${args[@]}"
