#!/bin/bash

if hash direnv 2>/dev/null; then
  echo "direnv is already installed"
  direnv version
  exit 0
fi

(
  set -eux

  url="https://github.com/direnv/direnv/releases/latest"
  latest=$(curl -fsSIL "$url" | tr -d '\r' | awk -F'/' '/^Location:/{print $NF}')

  url="https://github.com/direnv/direnv/releases/download/${latest}/direnv.linux-amd64"

  mkdir -p "$HOME/bin"
  curl -fsSL "$url" > "$HOME/bin/direnv" &&:

  #if [ $? -ne 0 ]; then
  #  url="https://github.com/direnv/direnv/releases/download/v2.6.0/direnv.linux-amd64"
  #  pp "direnv download ... $url"
  #  curl -fsSL "$url" > "$HOME/bin/direnv"
  #fi

  chmod +x "$HOME/bin/direnv"
)

echo
echo "direnv is installed"
direnv version
