#!/bin/bash

source "$(dirname "$0")/functions.sh"

###

if hash direnv 2>/dev/null; then
  pp "direnv is already installed"
  direnv version
  exit 0
fi

url="https://github.com/direnv/direnv/releases/latest"
pp "direnv detect latest ... ${url}"
latest=$(curl -fsSIL "$url" | tr -d '\r' | awk -F'/' '/^Location:/{print $NF}')

: ${latest:?}
pp "direnv latest version ... ${latest}"

url="https://github.com/direnv/direnv/releases/download/${latest}/direnv.linux-amd64"
pp "direnv download ... $url"
mkdir -p "$HOME/bin"
curl -fsSL "$url" > "$HOME/bin/direnv" &&:

if [ $? -ne 0 ]; then
  url="https://github.com/direnv/direnv/releases/download/v2.6.0/direnv.linux-amd64"
  pp "direnv download ... $url"
  curl -fsSL "$url" > "$HOME/bin/direnv"
fi

chmod +x $HOME/bin/direnv

pp "direnv has been installed on $HOME/bin/direnv"
direnv version
