#!/bin/bash

(
  set -eux

  url="https://github.com/docker/machine/releases/latest"
  latest=$(curl -fSIL "$url" | tr -d '\r' | awk -F'/' '/^Location:/{print $NF}')

  url="https://github.com/docker/machine/releases/download/${latest}/docker-machine-Linux-x86_64"

  tmp=$(mktemp -t docker-machine.XXXXXXXX)
  trap 'rm -f -- "$tmp"' EXIT

  curl -fSL "$url" > "$tmp" &&:

  install -D -m0755 "$tmp" "$HOME/bin/docker-machine"
)

echo
echo "docker-machine is installed"
docker-machine --version
