#!/bin/bash

source "$(dirname "$0")/functions.sh"

install-github-latest-release-tgz \
  'https://github.com/junegunn/fzf-bin/releases/latest' \
  'https://github.com/junegunn/fzf-bin/releases/download/${latest}/fzf-${latest}-linux_amd64.tgz' \
  'fzf' \
  'fzf' \
  'fzf --version'
