#!/bin/bash

if type fzf 1>/dev/null 2>&1; then
  echo "fzf is already installed"
  fzf --version 2>&1 | sed 's/^/  /'
  exit 0
fi

(
  set -eux

  latest=$(
    curl -fsSI "https://github.com/junegunn/fzf-bin/releases/latest" |
      tr -d '\r' |
      awk -F'/' '/^Location:/{print $NF}'
  )

  url="https://github.com/junegunn/fzf-bin/releases/download/${latest}/fzf-${latest}-linux_amd64.tgz"

  mkdir -p $HOME/bin
  curl -fsSL "${url}" | tar -xzf - --to-stdout fzf > $HOME/bin/fzf~

  mv $HOME/bin/fzf~ $HOME/bin/fzf
  chmod +x $HOME/bin/fzf
)

echo
echo "fzf is installed"
fzf --version 2>&1 | sed 's/^/  /'
