#!/bin/bash

source "$(dirname "$0")/functions.sh"

ius_release="ius-release-1.0-13"

###

if which git 1>/dev/null 2>&1; then
    pp "installed git"
    git --version
    exit 0
fi

if [ ! -f /etc/yum.repos.d/ius.repo ]; then
    if [ ! -f /etc/centos-release ]; then
        pp "centos only"
        exit 1
    fi

    version=$(rpm -qf /etc/centos-release --qf '%{version}')

    pp "install ius-release"
    sudo yum -y install \
        http://dl.iuscommunity.org/pub/ius/stable/CentOS/${version}/x86_64/${ius_release}.ius.centos${version}.noarch.rpm
fi

pp "install git2u"
sudo yum -y install git2u

git --version
