#!/bin/bash

if type ngrok 1>/dev/null 2>&1; then
  echo "ngrok is already installed"
  ngrok version
  exit 0
fi

(
  set -eux
  url=$(
    curl -fsSL "https://ngrok.com/download" |
      xmllint --xpath 'string(//*[@id="dl-linux-amd64"]//a/@href)' --html - 2>/dev/null
  )
  if [ -z "$url" ]; then
    exit 1
  fi

  url="${url%.*}.tgz"

  mkdir -p "$HOME/bin"
  curl -fsSL "$url" | tar xzf - --directory "$HOME/bin"
)

echo
echo "ngrok is installed"
ngrok version
