#!/bin/bash

source "$(dirname "$0")/functions.sh"

###

if [ ! -d "$HOME/.phpenv" ]; then
    pp "Install phpenv"
    curl -sSL https://raw.githubusercontent.com/CHH/phpenv/master/bin/phpenv-install.sh |
    bash
else
    pp "Update phpenv"
    curl -sSL https://raw.githubusercontent.com/CHH/phpenv/master/bin/phpenv-install.sh |
    UPDATE=yes bash
fi

mkdir -p "$HOME/.phpenv/plugins"
cd "$HOME/.phpenv/plugins"

plugins=(
    "php-build             https://github.com/CHH/php-build.git"
    "phpenv-composer       https://github.com/ngyuki/phpenv-composer.git"
    "phpenv-apache-version https://github.com/garamon/phpenv-apache-version.git"
)

for kv in "${plugins[@]}"; do
    kv=($kv)
    dir=${kv[0]}
    url=${kv[1]}

    if [ ! -d "$dir" ]; then
        pp "Install $dir"
        git clone "$url"
    else
        pp "Update $dir"
        cd "$dir"
        git pull "$url"
        cd - > /dev/null
    fi
    echo
done

# install patch-apxs2.sh
{
    pp "Install php-build-apxs2"

    mkdir -p php-build/share/php-build/before-install.d

    curl -sSL https://raw.githubusercontent.com/ngyuki/php-build-apxs2/master/patch-apxs2.sh > \
        php-build/share/php-build/before-install.d/patch-apxs2.sh

    chmod +x php-build/share/php-build/before-install.d/patch-apxs2.sh

    if ! grep -Ee '^--with-apxs2' php-build/share/php-build/default_configure_options > /dev/null; then
        echo "--with-apxs2" >> php-build/share/php-build/default_configure_options
    fi
}
