#!/bin/bash

set -eux
set -o pipefail

url=$(
  curl -fsSL 'https://www.terraform.io/downloads.html' | grep -Po 'https:\/\/releases\.hashicorp\.com\/terraform\/[.\d]+/terraform_[.\d]+_linux_amd64.zip'
)
if [ -z "$url" ]; then
  exit 1
fi

mkdir -p "$HOME/bin"
curl -fsSL "$url" | funzip > "$HOME/bin/terraform"
chmod +x "$HOME/bin/terraform"

echo
echo "terraform is installed"
terraform --version
