#!/bin/bash

source "$(dirname "$0")/functions.sh"

###

if type tmux-cssh 1>/dev/null 2>&1; then
  pp "tmux-cssh is already installed"
  exit 0
fi

url=https://raw.githubusercontent.com/dennishafemann/tmux-cssh/master/tmux-cssh

pp "tmux-cssh download ... $url"

mkdir -p $HOME/bin
curl -fsSL "$url" > $HOME/bin/tmux-cssh
chmod +x "$HOME/bin/tmux-cssh"

pp "tmux-cssh has been installed ... $HOME/bin/tmux-cssh"
