#!/bin/bash

source "$(dirname "$0")/functions.sh"

install-github-latest-release-tgz \
  'https://github.com/watchexec/watchexec/releases/latest' \
  'https://github.com/watchexec/watchexec/releases/download/${latest}/watchexec-${latest}-x86_64-unknown-linux-gnu.tar.xz' \
  'watchexec-${latest}-x86_64-unknown-linux-gnu/watchexec' \
  "watchexec" \
  "watchexec --version"
