#!/bin/bash

(
  set -eux

  url="https://github.com/watchexec/watchexec/releases/latest"
  latest=$(curl -fSIL "$url" | tr -d '\r' | awk -F'/' '/^Location:/{print $NF}')

  tmp=$(mktemp -t watchexec.XXXXXXXX)
  trap 'rm -f -- "$tmp"' EXIT

  url="https://github.com/watchexec/watchexec/releases/download/${latest}/watchexec-${latest}-x86_64-unknown-linux-gnu.tar.gz"
  curl -fSL "$url" | tar xzvf - --to-stdout "watchexec-${latest}-x86_64-unknown-linux-gnu/watchexec" > "$tmp"

  install -D -m0755 "$tmp" "$HOME/bin/watchexec"
)

echo
echo "watchexec is installed"
watchexec --version 2>&1 | sed 's/^/  /'
