"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

[character]
success_symbol = "[\\$](bold green)"
error_symbol   = "[\\$](bold red)"

[directory]
truncate_to_repo = false
truncation_length = 0
style = 'yellow'
# repo_root_style = 'bold yellow'
# before_repo_root_style = 'bold yellow'

[git_branch]
symbol = ''
style = 'purple'
format = '[\($symbol$branch\)]($style) '
# format = '[\($symbol$branch -> $remote_name/$remote_branch\)]($style)'
# always_show_remote = true
# only_attached = false

[git_commit]
style = 'red bold'
format = '[\(detached:$hash$tag\)]($style) '
tag_disabled = false
tag_symbol = ':'

[git_status]
ahead = '' # push.default=current だと期待した表示にならない

[aws]
symbol = 'AWS='
format = '[$symbol($profile)]($style) '
style =	'green'

[terraform]
symbol = 'TF='
format = '[$symbol$workspace]($style) '

[cmd_duration]
disabled = true

[git_metrics]
disabled = true

[php]
disabled = true

[nodejs]
disabled = true

[env_var.ANSIBLE_INVENTORY]
symbol = 'ANSIBLE_INVENTORY='
format = "[$symbol$env_value]($style) "
style =	'green'
