[settings]
experimental = true
disable_backends = ["asdf", "vfox"]

[tools]
act = "latest"
ansible = { version = "9", pipx_args = "--include-deps", uvx = "false" }
aqua = "latest"
"aqua:google.com/antigravity-cli" = "1.0.3-6260531212976128"
argo = "latest"
argo-rollouts = "latest"
bun = "latest"
carapace = "latest"
cloudflared = "latest"
dasel = "latest"
direnv = "latest"
ecspresso = "latest"
gcloud = "latest"
gh = "latest"
go-jsonnet = "latest"
gron = "latest"
hwatch = "latest"
k9s = "latest"
miller = "latest"
mutagen = "latest"
node = "24.16.0"
"npm:0x" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@googleworkspace/cli" = "latest"
"npm:@mermaid-js/mermaid-cli" = "latest"
"npm:@sasazame/ccresume" = "latest"
"npm:@upstash/context7-mcp" = "latest"
"npm:browser-sync" = "latest"
"npm:context-mode" = "latest"
"npm:diff2html-cli" = "latest"
"npm:difit" = "latest"
"npm:json2yaml" = "latest"
"npm:markdown-pdf" = "latest"
"npm:serverless" = "latest"
"npm:source-map-explorer" = "latest"
"npm:strip-ansi-cli" = "latest"
"npm:ts-node" = "latest"
"npm:tsx" = "latest"
"npm:typescript" = "latest"
"npm:vsce" = "latest"
"npm:wsl-open" = "latest"
"npm:xml2json" = "latest"
packer = "latest"
pinact = "latest"
terraform = "latest"
terraform-docs = "latest"
tflint = "latest"
trivy = "latest"
yazi = "latest"
yq = "latest"
