#!/bin/bash

set -eu

: ${USER:?}

trash=/var/tmp/.${USER}.trash
today=$trash/$(date +%Y%m%d)

if [ ! -d "$today" ]; then
    mkdir -p "$today"
fi

if [ $# -eq 0 ]; then
  echo "$trash"
else
  mv --backup=numbered -- "$@" "$today"
fi
