#!/usr/bin/env bash

# Usage: phplive [options] [dir]
#
# Options:
#   -o         Open WebBrowser
#   -x         Disable LiveReload
#   -p port    Listening PortNumber on WebServer
#
# Arguments:
#   dir        Document Root
# END

set -ue

function usage()
{
    cat $0 | sed -r -n '
        /^# END/q
        /^# Usage/,//{
            s/^# ?//
            p
        }
    '
    exit 1
}

open=0
live=35729
port=9876
root=.
file=

while getopts oxp: OPT; do
    case $OPT in
        o)  open=1
            ;;
        x)  live=0
            ;;
        p)  port=$OPTARG
            ;;
        \?) usage
            ;;
    esac
done

shift $((OPTIND - 1))

if [ $# -gt 0 ]; then
    root=${1%/*}
    file=${1##*/}
fi

if [ "$open" -ne 0 ]; then
    if [ -n "$WINDIR" ]; then
        ( sleep 1 && start "http://127.0.0.1:$port/$file" )&
    else
        ( sleep 1 && open "http://127.0.0.1:$port/$file" )&
    fi
fi

if [ "$live" -ne 0 ]; then
    livereloadx -p $port -y http://localhost:$live &
    php -S "0.0.0.0:$live" -t "$root"
else
    php -S "0.0.0.0:$port" -t "$root"
fi
