#!/usr/bin/env bash

# Usage: phplive [options] [dir]
#
# Options:
#   -o         Open WebBrowser
#   -x         Enable LiveReload
#   -p port    Listening PortNumber on WebServer
#
# Arguments:
#   dir        Document Root
# END

set -ue

function usage()
{
    cat $0 | sed -r -n '
        /^# END/q
        /^# Usage/,//{
            s/^# ?//
            p
        }
    '
    exit 1
}

open=0
live=0
port=80
root=.

while getopts oxp: OPT; do
    case $OPT in
        o)  open=1
            ;;
        x)  live=1
            ;;
        p)  port=$OPTARG
            ;;
        \?) usage
            ;;
    esac
done

shift $((OPTIND - 1))

if [ $# -gt 0 ]; then
    root=${1%/}
fi

if [ "$live" -ne 0 ]; then
    livereloadx &
fi

if [ "$open" -ne 0 ]; then
    if [ -n "$WINDIR" ]; then
        ( sleep 1 && start "http://127.0.0.1:$port/" )&
    else
        ( sleep 1 && open "http://127.0.0.1:$port/" )&
    fi
fi

php -S "0.0.0.0:$port" -t "$root"
