#!/bin/bash

set -e

function usage()
{
    echo "Usage: $(basename "$0") <command> [path]" 1>&2
    exit 1
}

if [ ! -x "$TGIT_BIN_DIR" ]; then
    echo "You should be set \$TGIT_BIN Environment variable." 1>&2
    exit 1
fi

if [ -z "$1" ]; then
    usage
fi

command=

case "$1" in
    status)
        command=repostatus
        ;;
    *)
        command=$1
        ;;
esac

path=

if [ -z "$2" ]; then
    path=.
else
    path=$2
fi

start "" "$TGIT_BIN_DIR\\TortoiseGitProc.exe" "/command:$command" "/path:$path"
